### ISSUE TITLE
Upgrade the Solidity version

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#11]
Hey team,

I'm thinking about importing Linea base contracts and interfaces directly from [their repository](https://github.com/Consensys/linea-contracts). However, there's an issue: Linea contracts require Solidity v0.8.19, while our repo is on v0.8.15.

We chose this version to match the [original state bridge repo](https://github.com/worldcoin/world-id-state-bridge/blob/main/foundry.toml). But do we really need to stick with v0.8.15, or can we upgrade to v0.8.19?

-------

Updates from smart guys in the comments:
- Yes we can "safely" upgrade the compiler because `world-id-state-bridge` contracts use caret version
- Solidity changelog (we need to read between these two anchors):
    - v0.8.15: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0815-2022-06-15
    ...
    - v0.8.19: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0819-2023-02-22

**Comment by Jemiiah** [comment]
I would love to work on this issue

**Comment by Jemiiah** [comment]
also @kfastov i think we need to upgrade the repo to the 0.8.19 version cause i think linea contracts is not backwards compatible so it’s best to upgrade your implementation to 0.8.19 or use the caret to make your contracts forward compatible ^0.8.15

**Comment by Jemiiah** [comment]
does this answer satisfy your question ser?

**Comment by kfastov** [comment]
Hi @Jemiiah ! That's a good point. Also we'll be able to use more recent release versions of OZ and other dependencies.
But I think it's better to start working on this issue after merging all pending PRs.

**Comment by Jemiiah** [comment]
That sounds like a solid plan. Merging all pending PRs first will help avoid potential conflicts and ensure a smoother transition when you upgrade the Solidity version.

**Comment by KodeSage** [comment]
Hi @kfastov , I think we should upgrade to 0.8.19, so it can be compatible with the linear contracts.

also I the original state bridge repo is compatible with latter versions too.

**Comment by piavgh** [comment]
if they did the semver right, upgrading from 0.8.15 to 0.8.19 will cause no backward incompatible issue (we only update the patch version - `major.minor.patch`)
But it's safer to check Solidity changelog carefully before proceeding
v0.8.15: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0815-2022-06-15
...
v0.8.19: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0819-2023-02-22

**Comment by kfastov** [comment]
@Jemiiah the PRs are merged now, and I can assign this issue to you if you want, but I want to warn you that it's no longer part of ODHack because it's over

**Comment by Jemiiah** [comment]
sorry @kfastov i saw this information late I would love to take the work still

**Comment by Jemiiah** [comment]
also @kfastov  what does that mean if it’s no longer part of ODHack

**Comment by kfastov** [comment]
> also @kfastov what does that mean if it’s no longer part of ODHack

Hi @Jemiiah ! It means that I can't guarantee that this contribution will be 100% rewarded 😄

**Comment by Jemiiah** [comment]
okay that still sounds promising 😂😂
I’ll get right into 🚀🚀

**Comment by kfastov** [comment]
Cool cool!
I'll change the description a bit to better fit the goal

**Comment by kfastov** [comment]
I think it can be closed now
