### ISSUE TITLE
Add the schema of the state bridge

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#12]
Draw a schema like [this](https://github.com/worldcoin/world-id-state-bridge/blob/main/docs/state-bridge.svg)
It should feature `WoridIDIdentityManager`, `LineaStateBridge` and `LineaWorldID`, and no other chains except for Ethereum and Linea.
The schema will be used in Readme and docs

Possible tool: https://app.diagrams.net/

**Comment by Jemiiah** [comment]
I would love to work on this

**Comment by Ejembiii** [comment]
I can work on this issue @kfastov

**Comment by kfastov** [comment]
@Iwueseiter You're welcome!
