### ISSUE TITLE
Add proper documentation for the bridge

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#14]
- Create `docs` directory
- Write spec for the state bridge (you may look at Worldcoin's [repo](https://github.com/worldcoin/world-id-state-bridge) as a reference)
- Describe unique features of this exact bridge, and changes to the protocol, llke using Linea's messaging system instead of `CrossDomainOwnable`

**Comment by kateberryd** [comment]
Hi @kfastov

**Comment by Gift-Naomi** [comment]
Hi
