### ISSUE TITLE
Write the deploy script for all contracts

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#15]
We need to create the deploy script for automating the deployment process across multiple networks and managing various configuration settings.
- It should read the configuration from the `json` configuration file (defaults) and environment variables (overrides).
- It should be able to deploy contracts to mainnet, testnet and local devnet
- You may adapt the [script](https://github.com/worldcoin/world-id-state-bridge/blob/main/src/script/deploy.js) from the `world-id-state-bridge` repo (if the license permits it)

Useful links:
[Deploy script](https://github.com/worldcoin/world-id-state-bridge/blob/main/src/script/deploy.js) from World ID State bridge repo
[PaulRBerg's template](https://github.com/PaulRBerg/foundry-template/)

**Comment by EjembiEmmanuel** [comment]
@kfastov I'd be happy to work on this

**Comment by kfastov** [comment]
@EjembiEmmanuel Hi! Do you have progress with this issue?

**Comment by EjembiEmmanuel** [comment]
@kfastov working on it. Will push some changes this week
