### ISSUE TITLE
Fix tests (and/or contracts that don't pass them)

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#59]
Problem: tests don't pass
Reason: either tests have bugs or contracts do, or maybe both
Solution: investigate and fix the bugs wherever they are

**Comment by kfastov** [comment]
3... 2...

**Comment by Oshioke-Salaki** [comment]
Cv

**Comment by kfastov** [comment]
Hi @Oshioke-Salaki It would be great but it's urgent and I am already working on it 😁

**Comment by kfastov** [comment]
I want to fix it today, I just created an issue for clarity, sorry
