### ISSUE TITLE
Write service in JS (or TS) for relaying roots from L1 to L2

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#65]
Requirements:
- Create single autonomous service that will scheedule itself and relay roots periodically
- Place the code under the single directory (src/service/root-relayer), take all relevant js scripts and move there
- Use existing scripts/modules where possible:
    - src/services/lineaStateBridgeEventListener.js
    - src/services/L2AnchorEventsMonitor.js
    - src/script/js/claimMessageModule.js
    - scripts/LineaRootPropagator.js
- Write maintainable, well-organized code. If you use LLM-based tools like ChatGPT or Cursor to write parts of the code, that's fine, just make sure the final code is tested and high quality and you understand what it's doing

Algorithm for the service:
- Load private key and other settings
- Wait for preconfigured time interval
- Propagate root on L1 (like in [LineaRootPropagator](scripts/LineaRootPropagator.js))
- Wait for L1 message to be sent ([lineaStateBridgeEventListener](src/services/lineaStateBridgeEventListener.js))
- Wait for message to arrive on L2 ([L2AnchorEventsMonitor](src/services/L2AnchorEventsMonitor.js)), memorize its parameters
- Claim this message on L2 (like in [LineaRootPropagator](scripts/LineaRootPropagator.js))

This issue description was edited (promise kept)

**Comment by ikemHood** [comment]
L

**Comment by Iwueseiter** [comment]
Hi @kfastov can I work on this?

**Comment by Jemiiah** [comment]
I would love to work on this issue @kfastov

**Comment by Gift-Naomi** [comment]
@kfastov Can I be assign to work on this please?

**Comment by ShantelPeters** [comment]
Please can I be assigned to work on this issue @kfastov
